### PR TITLE
Change long example to "ê-kî-nitawi-kâh-kîmôci-kotiskâwêyâhk"

### LINKED ISSUE #150: Use a better example on the front page than "they habitually go on very large hunts"
Right now, as an example of a "complicated word", we have this example: "ê-mâh-misi-nâh-nôcihikocik". I'm pretty sure we got this from some of Arok's materials, but it's kind of... violent? I don't feel like it's something we'd want to have on the front page 😅

Any ideas, @aarppe?

### PR DESCRIPTION
**Pull request by eddieantonio**
Closes #150.

### CODE REVIEW

**Comment by eddieantonio** [comment]
goshdarnit

**Comment by eddieantonio** [comment]
D'oh!

I used the _latest_ dictionary content to make the test DB and one of the unit tests was depending on the old content. I'll fix that in a different PR 😩

**Comment by eddieantonio** [comment]
Blocked by #275.

**Comment by Madoshakalaka** [comment]
but today is a holiday

**Comment by eddieantonio** [comment]
This is blocked by #275, which is in turn blocked by #274. Not until BOTH issues are resolved can this PR be reviewed 😩

**Pull request closed without merging**
