### PR TITLE
Update verb-ai-full.layout

### PR DESCRIPTION
**Pull request by aarppe**
This update will modify the tense marking to using prefixal preverbs, which matches the latest FST revamp.

### CODE REVIEW

**Comment by Madoshakalaka** [comment]
@aarppe I'll generate the layout manually and commit under this same branch so that the layout change reflects on our app. The same goes for #473

**Comment by aarppe** [comment]
@Madoshakalaka This needs to be updated at the same time as the FST is updated, alongside the layouts (and perhaps paradigms) for all verb word-classes. There is a reason I was turning this into its separate branch. I was trying to have one branch covering changes to the layout and paradigm files for all verbs, but wasn't able to figure out yet how to combine these together. So, do not manually merge this (yet), as it will break things, since the current FST is not able to generate the forms in the layout.

**Comment by Madoshakalaka** [comment]
@aarppe 
>  I'll generate the layout manually
I was referring to `res/prefilled_layouts` as those are paradigms full of proper fst analyses generated by our scripts.

**Comment by Madoshakalaka** [comment]
@aarppe 

> I'll generate the layout manually

I was referring to `CreeDictionary/res/prefilled_layouts` as those are paradigms full of proper fst analyses generated by our scripts, from `CreeDictionary/res/layouts`.

For the FST updates, you may just want to just replace the fomabin/hfstol files under `CreeDictionary/res/fst`, in this same branch. We do have automated pull requests set up so that normally a PR with the newst foma/hfstol files will be submitted whenever the `plains-cree-fst` publishes a new release ([releases here](https://github.com/UAlbertaALTLab/plains-cree-fsts/releases)). But if you wish to manually update in this branch. That's OK too.

But otherwise, from our programs prospective, I don't think updating the layouts or the FST breaks stuff, thought one may not want to do so, at least it won't interrupt our App from running. If the layouts/fst files are inconsistent, the worst consequence is empty/wrong cells on the paradigm page.

Normally if continuous-integration passes with a green tick, the app will run with no problem with the PR

checks-new

The failed task is the "coverage check" for the PR. It indicates that with this PR, the tests covers fewer lines in our code. It is a minor concern in this case and shouldn't stop this PR from merging.

That said, we agreed on a routine where the PR submitter decides when to merge. So no worries! I won't merge it arbitrarily.

**Comment by aarppe** [comment]
> For the FST updates, you may just want to just replace the fomabin/hfstol files under CreeDictionary/res/fst, in this same branch. We do have automated pull requests set up so that normally a PR with the newst foma/hfstol files will be submitted whenever the plains-cree-fst publishes a new release (releases here). But if you wish to manually update in this branch. That's OK too.

I'd like to set up a branch where the update to the FSTs as well as the changes to the *.paradigm and *.layout files (all layouts for verbs) will be undertaken in one go, once all the necessary changes have been made. If either the layouts or FST are changes prematurely, then something will break.

The changes involve in the case of `+Prs` just removing that feature (since their is no present tense preverb), and in the case of +`Prt`, `+Fut+Int `and `+Fut+Def` removing the suffixal features and instead adding the preverbs `PV/ki+`, `PV/wi+` and `PV/ka+`. This also means removing the +Prs feature from some of the Conjunct forms, where the actual tense/mood is indicated by the preverbs `PV/ka+` and `PV/ta+`.

One question I am wondering is how well with the minimal layouts work in the case of the present tense reference in the layouts, as e.g. `+Ind+1Sg` would refer to any one of `*+V+AI+Prs+Ind+1Sg`, `PV/ki+*+V+AI+Prs+Ind+1Sg`, `PV/wi+*+V+AI+Prs+Ind+1Sg`, and `PV/ka+*+V+AI+Prs+Ind+1Sg`.

The same problem applies to the neutral Conjunct case, as many Conjunct forms have the preverb `PV/e+`, and the neutral form does not have any other preverb to distinguish it from the tensed ones.

Is there some wild-card that we can use in the *.layout specifications that would mean that the layout cell must match all the features in the *.paradigm file, with the exclusion of the lemma? E.g. `=+V+AI+Ind+1Sg` matches only `{{ lemma }+V+AI+Ind+1Sg`, and not the preverbed cases. Or e.g. `=PV/e+*+V+AI+Cnj+1Sg` matches only `PV/e+{{ lemma }+V+AI+Ind+1Sg`, and not the tensed cases?

**Pull request closed without merging**
