### PR TITLE
Action: eslint

### PR DESCRIPTION
**Pull request by eddieantonio**
Runs eslint after each commit to master!

### CODE REVIEW

**Comment by kobexamoh** [comment]
All my semicolons,,,gone with the wind ✨

**Comment by eddieantonio** [comment]
> All my semicolons,,,gone with the wind ✨

Honestly, I hate the fact that most modern JavaScript style guides do away with semicolons — I like semicolons! But nixing semicolons is more consistent 🙄

**Comment by eddieantonio** [comment]
> LGTM! Do we have to add/change anything on our local machines to comply with this (like, should it be part of our commit process now at all)?

Nope! No changes at all! `eslint` is run **when a PR is merged into master**. So literally no change to your workflow, except, you have to be mindful that after a PR is merged, you should based your future changes on the current state of master.

**Comment by eddieantonio** [comment]
Blocked by #441; I'm gonna wait for that one to land, because merging this and then merging #441 will likely lead to conflicts

**Comment by kobexamoh** [comment]
Got it! Hoping to wrap that up in a couple of hours on returning home.

**Pull request merged**
