### PR TITLE
new fst releases available

### PR DESCRIPTION
**Pull request by Madoshakalaka**
this pull request is automated and triggered by new fst releases

### CODE REVIEW

**Comment by eddieantonio** [comment]
The GitHub Action is a bit overzealous when it removes FSTs; e.g., it removes FSTs we're using!

https://travis-ci.org/UAlbertaALTLab/cree-intelligent-dictionary/jobs/652743449#L316

So part of the fix for this is to make the GitHub action a bit less destructive! :joy:

**Comment by Madoshakalaka** [comment]
@eddieantonio no problem. ez fix

**Comment by Madoshakalaka** [comment]
@eddieantonio actually, the [latestest release](https://github.com/UAlbertaALTLab/plains-cree-fsts/releases/tag/20200217) does NOT have a `crk-normative-generator.hfstol`

Is it true that sometimes certain files won't be included in the releases?

**Comment by eddieantonio** [comment]
> @eddieantonio actually, the [latestest release](https://github.com/UAlbertaALTLab/plains-cree-fsts/releases/tag/20200217) does NOT have a `crk-normative-generator.hfstol`
> 
> Is it true that sometimes certain files won't be included in the releases?

No, I think this is my bad. I'll fix it in Plains Cree FSTs.

**Comment by eddieantonio** [comment]
wtf

https://github.com/UAlbertaALTLab/plains-cree-fsts/blob/master/.travis.yml#L40

**Comment by eddieantonio** [comment]
> Is it true that sometimes certain files won't be included in the releases?

Captura de Pantalla 2020-02-20 a la(s) 5 53 07 p  m

APPARENTLY! This file was uploaded to the release, but the upload failed??? Wow, systems fail sometimes! I'll update the release manually.

**Comment by eddieantonio** [comment]
Hey @Madoshakalaka: can we make the action fail if it can't download all of the FSTs it expects? I guess, sometimes there are upload failures!

**Comment by eddieantonio** [comment]
Closing in favour of #289.

**Comment by Madoshakalaka** [comment]
> Hey @Madoshakalaka: can we make the action fail if it can't download all of the FSTs it expects? I guess, sometimes there are upload failures!

@eddieantonio I'm no bash guru but I'll try

**Comment by Madoshakalaka** [comment]
@eddieantonio actually I think it's better to produce the pull request and let the CI fail, compared to not  producing the pull request at all. The latter is the same as failing silently.

**Comment by eddieantonio** [comment]
> @eddieantonio actually I think it's better to produce the pull request and let the CI fail, compared to not producing the pull request at all. The latter is the same as failing silently.

Good point! Okay, we'll let CI fail!  😂

**Pull request closed without merging**
