### PR TITLE
new fst releases available

### PR DESCRIPTION
**Pull request by Madoshakalaka**
this pull request is automated and triggered by new fst releases

### CODE REVIEW

**Comment by eddieantonio** [comment]
@aarppe, please decide whether to merge this. The tests have not finished yet, but assuming they all pass, this should be okay to merge, and will not break... _much_!

If things are broken on the production website, we can go back to this pull request and revert it! That's all it takes to undo the damage!

**Comment by eddieantonio** [comment]
@aarppe **DO NOT MERGE THIS**. It broke everything!

**Comment by Madoshakalaka** [comment]
lol I'll try to investigate what happened

**Comment by aarppe** [comment]
I was in meetings, so I did not approve not merge, which was fortunate, it seems.

Nevertheless, obviously needs investigating.

**Comment by eddieantonio** [comment]
@Madoshakalaka I think this is caused by a bug in fst-lookup... 😩

**Comment by Madoshakalaka** [comment]
@eddieantonio uhuhu I'll let you have a look first then?

**Comment by eddieantonio** [comment]
@aarppe might try a simpler FST with less non-Cree stuff.

**Comment by aarppe** [comment]
I left out the proper names and abbreviations from the catenation of the LEXC source, leaving otherwise the compilation script the same and adding FOMA compilation at the end. Direct conversion with `hfst-fst2fst` of the HFST descriptive analyzer to FOMA format results in abort, but the following scheme seems to work:

```
hfst-fst2fst -b -F -i crk-gen-norm-dict.hfst -o crk-gen-norm-dict.fomabin

hfst-fst2fst -b -F -i crk-orth.hfst -o crk-orth.fomabin

foma -e"load crk-gen-norm-dict.fomabin" -e"define M" -e"load crk-orth.fomabin" -e"invert net" -e"define O" -e"regex [ M .o. O ];" -e"save stack crk-anl-desc-dict.fomabin" -s
```

Testing with a few examples, we seem to get results we expect:

```
flookup -q crk-anl-desc-dict.fomabin
nepat
nipayan
meyonipat
nepat	IC+nipâw+V+AI+Cnj+Prs+3Sg

nipayan	pê-ayâw+V+AI+Ind+Prs+1Sg
nipayan	nipâw+V+AI+Cnj+Prs+2Sg
nipayan	nipâw+V+AI+Cnj+Prs+1Sg

meyonipat	IC+PV/miyo+nipâw+V+AI+Cnj+Prs+3Sg
```

That `hfst-fst2fst` produces an imperfect FST is something that we ought to bring to the attention of the Helsinki folks.  Nevertheless, the HFST and FOMA FSTs seem to work, so I can't easily judge if there's something disagreeable in the source code.

Regardless, I don't know if this works with the python FST lookup code.

Getting the new FST working is important as it fixes some key errors in the affixation implemented last week (Atticus is working in the remaining issues, namely unspecified actors for VAIs and VTIs) as well as incorporates all of Arok's new dictionary entries.

**Comment by eddieantonio** [comment]
I'm closing this PR, as making a new build script seems to be a something we should figure out in [UAlbertaALTLab/plains-cree-fsts](https://github.com/UAlbertaALTLab/plains-cree-fsts), and within Giella. The FSTs uploaded in this pull request will simply not work :/

**Pull request closed without merging**
